# Part A: Build a baseline model

In [44]:
#determing the compressive strength of a given concrete sample based on its ingredients

The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:

1. Cement

2. Blast Furnace Slag

3. Fly Ash

4. Water

5. Superplasticizer

6. Coarse Aggregate

7. Fine Aggregate

In [1]:
#importing the pandas and the Numpy libraries.
import pandas as pd
import numpy as np

In [2]:
#download the data and read it into a pandas dataframe.
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
#check how many data points we have.
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
#Split data into predictors and target
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [7]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [19]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [20]:
n_cols = predictors.shape[1]

In [11]:
conda install tensorflow

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [12]:
conda install keras

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [13]:
import keras

Using TensorFlow backend.
C:\Users\palak\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\palak\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [22]:
# build the model
model = regression_model()

In [24]:
# fit the model
#we will train and test the model at the same time using the fit method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.
loss_list = np.array([])

for i in range(1,51):
    model.fit(predictors, target, validation_split=0.3, epochs=50, verbose=0)
    results = model.evaluate(predictors, target)
    print(results)
    loss_list = np.append(loss_list, results)

print(loss_list)

1030/1030 [==============================] - 0s 21us/step
231.01863668497327
1030/1030 [==============================] - 0s 25us/step
172.74666297690382
1030/1030 [==============================] - 0s 22us/step
138.72546900776985
1030/1030 [==============================] - 0s 16us/step
119.46121043233038
1030/1030 [==============================] - 0s 22us/step
103.52019318145456
1030/1030 [==============================] - 0s 22us/step
78.27309146621852
1030/1030 [==============================] - 0s 48us/step
63.113591710803576
1030/1030 [==============================] - 0s 22us/step
57.41938221014819
1030/1030 [==============================] - 0s 34us/step
55.37780915047359
1030/1030 [==============================] - 0s 25us/step
56.620360061497365
1030/1030 [==============================] - 0s 16us/step
56.899566657797806
1030/1030 [==============================] - 0s 20us/step
63.462859737062914
1030/1030 [==============================] - 0s 22us/step
66.7527449968949
1030/1030 [==============================] - 0s 15us/step
58.84262696793936
1030/1030 [==============================] - 0s 21us/step
56.87808911221698
1030/1030 [==============================] - 0s 27us/step
77.96503449967764
1030/1030 [==============================] - 0s 28us/step
57.409663613328654
1030/1030 [==============================] - 0s 22us/step
58.43603345259879
1030/1030 [==============================] - 0s 24us/step
61.39471552580306
1030/1030 [==============================] - 0s 23us/step
57.35450809812083
1030/1030 [==============================] - 0s 21us/step
64.20248731594641
1030/1030 [==============================] - 0s 22us/step
64.83676104499298
1030/1030 [==============================] - 0s 25us/step
66.04931344337834
1030/1030 [==============================] - 0s 23us/step
58.59720143438543
1030/1030 [==============================] - 0s 22us/step
67.47823507068226
1030/1030 [==============================] - 0s 24us/step
74.15870669466779
1030/1030 [==============================] - 0s 23us/step
58.75514643400618
1030/1030 [==============================] - 0s 22us/step
69.61043398958965
1030/1030 [==============================] - 0s 24us/step
61.32221906347182
1030/1030 [==============================] - 0s 22us/step
59.33863297249507
1030/1030 [==============================] - 0s 22us/step
80.78703817719395
1030/1030 [==============================] - 0s 23us/step
77.38379495861462
1030/1030 [==============================] - 0s 24us/step
59.51124020178341
1030/1030 [==============================] - 0s 26us/step
64.50378863880935
1030/1030 [==============================] - 0s 22us/step
65.31934515203088
1030/1030 [==============================] - 0s 22us/step
61.45041986854331
1030/1030 [==============================] - 0s 23us/step
60.23768153514677
1030/1030 [==============================] - 0s 22us/step
61.375132203333585
1030/1030 [==============================] - 0s 23us/step
71.82304494913342
1030/1030 [==============================] - 0s 24us/step
61.86758141378755
1030/1030 [==============================] - 0s 23us/step
65.55091868280208
1030/1030 [==============================] - 0s 21us/step
64.58914565299321
1030/1030 [==============================] - 0s 20us/step
66.36307155275807
1030/1030 [==============================] - 0s 30us/step
60.13610137643166
1030/1030 [==============================] - 0s 21us/step
64.20968005726638
1030/1030 [==============================] - 0s 23us/step
63.67973779474647
1030/1030 [==============================] - 0s 20us/step
77.88607770308708
1030/1030 [==============================] - 0s 19us/step
80.67602915347202
1030/1030 [==============================] - 0s 22us/step
61.224092590924606
1030/1030 [==============================] - 0s 19us/step
66.59366120273627
[231.01863668 172.74666298 138.72546901 119.46121043 103.52019318
  78.27309147  63.11359171  57.41938221  55.37780915  56.62036006
  56.89956666  63.46285974  66.752745    58.84262697  56.87808911
  77.9650345   57.40966361  58.43603345  61.39471553  57.3545081
  64.20248732  64.83676104  66.04931344  58.59720143  67.47823507
  74.15870669  58.75514643  69.61043399  61.32221906  59.33863297
  80.78703818  77.38379496  59.5112402   64.50378864  65.31934515
  61.45041987  60.23768154  61.3751322   71.82304495  61.86758141
  65.55091868  64.58914565  66.36307155  60.13610138  64.20968006
  63.67973779  77.8860777   80.67602915  61.22409259  66.5936612 ]

In [25]:
import statistics as stat 

print("The mean of the MSEs is", np.mean(loss_list))
print("The standard deviation of the MSEs is", stat.stdev(loss_list))

The mean of the MSEs is 73.42377939746449
The standard deviation of the MSEs is 31.186530227999064

# Part B:  Normalize the data

In [26]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [27]:
n_cols_norm = predictors_norm.shape[1] # number of predictors

In [31]:

def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols_norm,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [32]:
model_norm = regression_model()
loss_list_norm = np.array([])

for i in range(1,51):
    model_norm.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=0)
    results_norm = model_norm.evaluate(predictors_norm, target)
    print(results_norm)
    loss_list_norm = np.append(loss_list_norm, results_norm)

print(loss_list_norm)

1030/1030 [==============================] - 0s 23us/step
398.827224346272
1030/1030 [==============================] - 0s 22us/step
198.45287368922558
1030/1030 [==============================] - 0s 24us/step
135.81371504404012
1030/1030 [==============================] - 0s 24us/step
95.46515330342413
1030/1030 [==============================] - 0s 21us/step
70.98064702228434
1030/1030 [==============================] - 0s 22us/step
58.43244117903478
1030/1030 [==============================] - 0s 24us/step
53.5248131103886
1030/1030 [==============================] - 0s 22us/step
51.820050608070154
1030/1030 [==============================] - 0s 25us/step
51.08411891529861
1030/1030 [==============================] - 0s 21us/step
50.51334756647499
1030/1030 [==============================] - 0s 24us/step
50.36059178472723
1030/1030 [==============================] - 0s 32us/step
50.82862836967394
1030/1030 [==============================] - 0s 25us/step
50.957471703094186
1030/1030 [==============================] - 0s 22us/step
51.923998090132926
1030/1030 [==============================] - 0s 27us/step
51.544441889790654
1030/1030 [==============================] - 0s 32us/step
51.704545608076074
1030/1030 [==============================] - 0s 24us/step
51.98316860754513
1030/1030 [==============================] - 0s 25us/step
51.668507696355434
1030/1030 [==============================] - 0s 21us/step
52.26191249217802
1030/1030 [==============================] - 0s 22us/step
52.304733261552826
1030/1030 [==============================] - 0s 15us/step
52.54777208346765
1030/1030 [==============================] - 0s 34us/step
53.27501222184561
1030/1030 [==============================] - 0s 23us/step
53.28012524947379
1030/1030 [==============================] - 0s 21us/step
53.799995392734566
1030/1030 [==============================] - 0s 24us/step
53.703739529211546
1030/1030 [==============================] - 0s 26us/step
53.851429955936176
1030/1030 [==============================] - 0s 23us/step
52.77500194068094
1030/1030 [==============================] - 0s 17us/step
53.24725241059239
1030/1030 [==============================] - 0s 16us/step
53.28207915963478
1030/1030 [==============================] - 0s 14us/step
53.0410675789546
1030/1030 [==============================] - 0s 17us/step
52.56685582133173
1030/1030 [==============================] - 0s 21us/step
53.218780532392486
1030/1030 [==============================] - 0s 16us/step
53.09391903182835
1030/1030 [==============================] - 0s 16us/step
53.70133327743382
1030/1030 [==============================] - 0s 14us/step
53.97195590121075
1030/1030 [==============================] - 0s 14us/step
54.53204187189491
1030/1030 [==============================] - 0s 27us/step
54.5158233346291
1030/1030 [==============================] - 0s 25us/step
55.03358392808044
1030/1030 [==============================] - 0s 26us/step
55.52268463431053
1030/1030 [==============================] - 0s 22us/step
56.272490210672025
1030/1030 [==============================] - 0s 26us/step
56.750356433461015
1030/1030 [==============================] - 0s 26us/step
56.69305719171913
1030/1030 [==============================] - 0s 24us/step
56.944264058233465
1030/1030 [==============================] - 0s 26us/step
56.83555768948157
1030/1030 [==============================] - 0s 22us/step
56.98412401514146
1030/1030 [==============================] - 0s 22us/step
57.110207063249014
1030/1030 [==============================] - 0s 24us/step
57.675112085434996
1030/1030 [==============================] - 0s 24us/step
57.27861467379968
1030/1030 [==============================] - 0s 20us/step
57.41026365409777
1030/1030 [==============================] - 0s 22us/step
58.151910400390626
[398.82722435 198.45287369 135.81371504  95.4651533   70.98064702
  58.43244118  53.52481311  51.82005061  51.08411892  50.51334757
  50.36059178  50.82862837  50.9574717   51.92399809  51.54444189
  51.70454561  51.98316861  51.6685077   52.26191249  52.30473326
  52.54777208  53.27501222  53.28012525  53.79999539  53.70373953
  53.85142996  52.77500194  53.24725241  53.28207916  53.04106758
  52.56685582  53.21878053  53.09391903  53.70133328  53.9719559
  54.53204187  54.51582333  55.03358393  55.52268463  56.27249021
  56.75035643  56.69305719  56.94426406  56.83555769  56.98412402
  57.11020706  57.67511209  57.27861467  57.41026365  58.1519104 ]

In [33]:
## Calculate Mean and Standard Deviation of MSEs

print("The mean of the MSEs is", np.mean(loss_list_norm))
print("The standard deviation of the MSEs is", stat.stdev(loss_list_norm))
print("The mean of the MSEs improved by", np.mean(loss_list)-np.mean(loss_list_norm), "which is a", 100-np.mean(loss_list_norm)/np.mean(loss_list)*100, "percent improvement.")

The mean of the MSEs is 66.5503759123793
The standard deviation of the MSEs is 53.6103849049107
The mean of the MSEs improved by 6.873403485085191 which is a 9.361277152293454 percent improvement.

# Part C: Increase the number of epochs

In [34]:
## Train and Test model

model2_norm = regression_model()
loss_list_norm2 = np.array([])

for i in range(1,51):
    model2_norm.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=0)
    results2_norm = model2_norm.evaluate(predictors_norm, target)
    print(results2_norm)
    loss_list_norm2 = np.append(loss_list_norm2, results2_norm)

print(loss_list_norm2)

1030/1030 [==============================] - 0s 21us/step
180.15579428070959
1030/1030 [==============================] - 0s 25us/step
80.7288542219736
1030/1030 [==============================] - 0s 20us/step
52.57202465186999
1030/1030 [==============================] - 0s 30us/step
48.75717655663352
1030/1030 [==============================] - 0s 25us/step
46.70195187503852
1030/1030 [==============================] - 0s 28us/step
45.810192741468114
1030/1030 [==============================] - 0s 24us/step
45.52236099983882
1030/1030 [==============================] - 0s 25us/step
44.92753538853914
1030/1030 [==============================] - 0s 37us/step
43.64564759708145
1030/1030 [==============================] - 0s 18us/step
43.25881960600325
1030/1030 [==============================] - 0s 17us/step
43.4807483561988
1030/1030 [==============================] - 0s 29us/step
43.389099276644515
1030/1030 [==============================] - 0s 31us/step
42.84862542754238
1030/1030 [==============================] - 0s 22us/step
44.32779171397385
1030/1030 [==============================] - 0s 19us/step
46.31478310001707
1030/1030 [==============================] - 0s 31us/step
47.457643290399346
1030/1030 [==============================] - 0s 27us/step
47.918282569959324
1030/1030 [==============================] - 0s 20us/step
48.147529327985154
1030/1030 [==============================] - 0s 30us/step
48.839870075114725
1030/1030 [==============================] - 0s 26us/step
49.9790731337464
1030/1030 [==============================] - 0s 25us/step
50.475979999431125
1030/1030 [==============================] - 0s 25us/step
51.17366735958359
1030/1030 [==============================] - 0s 27us/step
51.50503782994539
1030/1030 [==============================] - 0s 33us/step
51.12218493119027
1030/1030 [==============================] - 0s 25us/step
51.167929788237636
1030/1030 [==============================] - 0s 25us/step
51.697243196061514
1030/1030 [==============================] - 0s 21us/step
51.60158082536123
1030/1030 [==============================] - 0s 17us/step
51.99190377540959
1030/1030 [==============================] - 0s 41us/step
51.34816602688391
1030/1030 [==============================] - 0s 39us/step
50.995506479207755
1030/1030 [==============================] - 0s 40us/step
51.2089534574342
1030/1030 [==============================] - 0s 40us/step
51.56729831140018
1030/1030 [==============================] - 0s 26us/step
51.36354447151851
1030/1030 [==============================] - 0s 43us/step
51.57451134839104
1030/1030 [==============================] - 0s 22us/step
51.75780161144664
1030/1030 [==============================] - 0s 25us/step
51.57339154586051
1030/1030 [==============================] - 0s 22us/step
51.538115329186894
1030/1030 [==============================] - 0s 23us/step
51.762265488707904
1030/1030 [==============================] - 0s 24us/step
52.30597977129001
1030/1030 [==============================] - 0s 23us/step
51.84334107926748
1030/1030 [==============================] - 0s 23us/step
51.939486886922595
1030/1030 [==============================] - 0s 27us/step
51.614866371525146
1030/1030 [==============================] - 0s 20us/step
52.33773682233199
1030/1030 [==============================] - 0s 28us/step
52.249880803673015
1030/1030 [==============================] - 0s 23us/step
52.40651267338725
1030/1030 [==============================] - 0s 28us/step
52.273515823512405
1030/1030 [==============================] - 0s 25us/step
53.15928534350349
1030/1030 [==============================] - 0s 30us/step
53.11584210442108
1030/1030 [==============================] - 0s 22us/step
53.20991514631845
1030/1030 [==============================] - 0s 24us/step
53.173150916238434
[180.15579428  80.72885422  52.57202465  48.75717656  46.70195188
  45.81019274  45.522361    44.92753539  43.6456476   43.25881961
  43.48074836  43.38909928  42.84862543  44.32779171  46.3147831
  47.45764329  47.91828257  48.14752933  48.83987008  49.97907313
  50.47598     51.17366736  51.50503783  51.12218493  51.16792979
  51.6972432   51.60158083  51.99190378  51.34816603  50.99550648
  51.20895346  51.56729831  51.36354447  51.57451135  51.75780161
  51.57339155  51.53811533  51.76226549  52.30597977  51.84334108
  51.93948689  51.61486637  52.33773682  52.2498808   52.40651267
  52.27351582  53.15928534  53.1158421   53.20991515  53.17315092]

In [35]:
## Calculate Mean and Standard Deviation of MSEs

print("The mean of the MSEs is", np.mean(loss_list_norm2))
print("The standard deviation of the MSEs is", stat.stdev(loss_list_norm2))
print("The mean of the MSEs improved by", np.mean(loss_list_norm)-np.mean(loss_list_norm2), "which is a", 100-np.mean(loss_list_norm2)/np.mean(loss_list_norm)*100, "percent improvement.")

The mean of the MSEs is 52.99676799416773
The standard deviation of the MSEs is 19.122202435548825
The mean of the MSEs improved by 13.553607918211561 which is a 20.365937430701138 percent improvement.

# Part D: Increase the number of hidden layers

In [36]:
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols_norm,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [40]:
model3_norm = regression_model()
loss_list_norm3 = np.array([])

for i in range(1,51):
    model3_norm.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=0)
    results_norm3 = model3_norm.evaluate(predictors_norm, target)
    print(results_norm3)
    loss_list_norm3 = np.append(loss_list_norm3, results_norm3)

print(loss_list_norm3)

1030/1030 [==============================] - 0s 26us/step
134.65651829543623
1030/1030 [==============================] - 0s 27us/step
107.31409568045903
1030/1030 [==============================] - 0s 41us/step
77.75488235695848
1030/1030 [==============================] - 0s 40us/step
61.521269089041404
1030/1030 [==============================] - 0s 27us/step
52.94096104242269
1030/1030 [==============================] - 0s 28us/step
49.90606174098635
1030/1030 [==============================] - 0s 27us/step
48.19165121652548
1030/1030 [==============================] - 0s 29us/step
44.747658823994755
1030/1030 [==============================] - 0s 33us/step
43.0666287505511
1030/1030 [==============================] - 0s 16us/step
43.12972016936367
1030/1030 [==============================] - 0s 25us/step
46.38926094573678
1030/1030 [==============================] - 0s 20us/step
44.23447355992586
1030/1030 [==============================] - 0s 42us/step
43.28071635718484
1030/1030 [==============================] - 0s 26us/step
44.8042861419974
1030/1030 [==============================] - 0s 29us/step
45.03918053339986
1030/1030 [==============================] - 0s 23us/step
46.403327008589955
1030/1030 [==============================] - 0s 18us/step
46.20558802780596
1030/1030 [==============================] - 0s 37us/step
47.88132478288077
1030/1030 [==============================] - 0s 36us/step
48.29191341214967
1030/1030 [==============================] - 0s 29us/step
48.51825573374924
1030/1030 [==============================] - 0s 23us/step
49.86605177944146
1030/1030 [==============================] - 0s 28us/step
51.96284330053237
1030/1030 [==============================] - 0s 31us/step
52.7674729356488
1030/1030 [==============================] - 0s 28us/step
52.2792188699963
1030/1030 [==============================] - 0s 30us/step
51.27799911499024
1030/1030 [==============================] - 0s 24us/step
53.455805317406515
1030/1030 [==============================] - 0s 19us/step
51.185488343470304
1030/1030 [==============================] - 0s 32us/step
54.14145971501915
1030/1030 [==============================] - 0s 18us/step
54.47874106990481
1030/1030 [==============================] - 0s 26us/step
55.04984828615652
1030/1030 [==============================] - 0s 19us/step
52.96813338937111
1030/1030 [==============================] - 0s 28us/step
52.852020678473906
1030/1030 [==============================] - 0s 26us/step
53.16895577143697
1030/1030 [==============================] - 0s 26us/step
53.48179247217271
1030/1030 [==============================] - 0s 27us/step
57.014812439853706
1030/1030 [==============================] - 0s 27us/step
58.331557227569874
1030/1030 [==============================] - 0s 21us/step
56.652674006489875
1030/1030 [==============================] - 0s 31us/step
61.399810791015625
1030/1030 [==============================] - 0s 28us/step
63.17724661965972
1030/1030 [==============================] - 0s 24us/step
64.8913843247497
1030/1030 [==============================] - 0s 21us/step
64.55775110929915
1030/1030 [==============================] - 0s 24us/step
66.56207678341171
1030/1030 [==============================] - 0s 19us/step
65.18246734026566
1030/1030 [==============================] - 0s 28us/step
66.18323807207126
1030/1030 [==============================] - 0s 27us/step
69.29293137337397
1030/1030 [==============================] - 0s 28us/step
69.40897436049379
1030/1030 [==============================] - 0s 26us/step
73.38276510886776
1030/1030 [==============================] - 0s 23us/step
71.16627360223566
1030/1030 [==============================] - 0s 20us/step
72.07647723596072
1030/1030 [==============================] - 0s 30us/step
75.68708281285555
[134.6565183  107.31409568  77.75488236  61.52126909  52.94096104
  49.90606174  48.19165122  44.74765882  43.06662875  43.12972017
  46.38926095  44.23447356  43.28071636  44.80428614  45.03918053
  46.40332701  46.20558803  47.88132478  48.29191341  48.51825573
  49.86605178  51.9628433   52.76747294  52.27921887  51.27799911
  53.45580532  51.18548834  54.14145972  54.47874107  55.04984829
  52.96813339  52.85202068  53.16895577  53.48179247  57.01481244
  58.33155723  56.65267401  61.39981079  63.17724662  64.89138432
  64.55775111  66.56207678  65.18246734  66.18323807  69.29293137
  69.40897436  73.38276511  71.1662736   72.07647724  75.68708281]

In [43]:
## Calculate Mean and Standard Deviation of MSEs

print("The mean of the MSEs is", np.mean(loss_list_norm3))
print("The standard deviation of the MSEs is", stat.stdev(loss_list_norm3))
print("The mean of the MSEs improved by", np.mean(loss_list_norm)-np.mean(loss_list_norm3), "which is a", 100-np.mean(loss_list_norm3)/np.mean(loss_list_norm)*100, "percent improvement.")

The mean of the MSEs is 58.36362255842709
The standard deviation of the MSEs is 16.202311367400664
The mean of the MSEs improved by 8.186753353952206 which is a 12.301588445917929 percent improvement.